### PR TITLE
addMultiple functionality

### PR DESCRIPTION
**Pull request by MauriceButler**
Added an addMultiple function to allow multiple items to be added to the queue at once.

### CODE REVIEW

**Comment by tmcw** [comment]
@MauriceButler can you give an example where this is preferable to calling .add() repeatedly?

**Comment by MauriceButler** [comment]
Hi @tmcw

When I already have a large array of items, rather than having to loop over them and add one by one the array can just be concatenated in.

For instance the basic example in the readme, 

``` javascript
q.add('https://www.somewhere.com');
q.add('https://www.someplace.com');
q.add('https://www.something.com');
q.add('https://www.someother.com');
```

If the urls were already in an array, they could just be added in one go rather than looping or mapping over them.

``` javascript
var urls = [
    'https://www.somewhere.com',
    'https://www.someplace.com',
    'https://www.something.com',
    'https://www.someother.com'
];

q.addMultiple(urls);
```
vs 

``` javascript
var urls = [
    'https://www.somewhere.com',
    'https://www.someplace.com',
    'https://www.something.com',
    'https://www.someother.com'
];

for (var i = 0; i < urls.length; i++) {
    q.add(urls[i]);
}
```

With 4 items it doesn't seem like a big deal but when dealing with large jobs of ~2k items it is just unnecessary when they can be added in one go.

When I need a queue I almost always have my items in an array already, would be nice to just add them.

**Comment by tmcw** [comment]
You can use `.forEach` and `.bind` to do the same without the explicit for loop.

```js
var urls = [
    'https://www.somewhere.com',
    'https://www.someplace.com',
    'https://www.something.com',
    'https://www.someother.com'
];

urls.forEach(q.add.bind(q));
```

**Comment by MauriceButler** [comment]
Yes but the expense of the iteration is still there.

It is the iteration over the array that seems unnecessary.

**Comment by tmcw** [comment]
Closing; would accept a PR that includes both this functionality and a benchmark that demonstrates a repeatable real performance boost.

**Pull request closed without merging**
